<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE BookCatalog [
<!ELEMENT BookCatalog (Book*)>
<!ELEMENT Book ((BookCode | Title), CoAuthor, Year, Price, Summary)>
<!ELEMENT BookCode (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT CoAuthor (#PCDATA | Author)*>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Summary ANY>
<!ATTLIST Book lang CDATA #IMPLIED>
<!ATTLIST Price unit (원|달러|엔|프랑) #IMPLIED>
]>

<BookCatalog>
<Book lang = "kr">
<Title>불편한 편의점</Title>
<CoAuthor>
primary Author: <Author> 김호연 </Author>
secondary Author: <Author> 오지원 </Author>
</CoAuthor>
<Year>2021</Year>
<Price unit="원">15000</Price>
<Summary>청파동 골목 모퉁이의 작은 가게, 서울역 노숙인이었던 정체불명의 야간 알바가 지키는 곳, 불편한데 자꾸 가고 싶은 봄날의 편의점</Summary>
</Book>

<Book  lang = "eng">
<Title>물고기는 존재하지 않는다</Title>
<CoAuthor>
primary Author: <Author> 룰루 밀러</Author>
secondary Author: <Author> 마이크 </Author>
</CoAuthor>
<Year>2021</Year>
<Price unit="달러">15</Price>
<Summary>작가의 자전적 경험을 담은 논픽션 에세이</Summary>
</Book>

<Book  lang = "kr">
<Title>도시와 그 불확실한 벽</Title>
<CoAuthor>
primary Author: <Author> 무라카미 하루키</Author>
secondary Author: <Author> 사쿠라 </Author>
</CoAuthor>
<Year>2023</Year>
<Price unit="엔">1200</Price>
<Summary>첫 발표 이후 43년, 마음에 품어왔던 소설을 마침내 완성하다.
하루키적 상상력의 모든 것이 담긴 결정적 세계</Summary>
</Book>
</BookCatalog>